package blowfish;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author gryffin
 */
public class MainScreen extends javax.swing.JApplet {

    /**
     * Initializes the applet MainScreen
     */
    
    String key = "";
    File file = null;
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        getContentPane().setBackground(Color.BLACK);
        this.setSize(400, 300);

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(java.awt.Color.black);
        setPreferredSize(new java.awt.Dimension(400, 300));

        jButton1.setBackground(java.awt.Color.white);
        jButton1.setForeground(java.awt.Color.blue);
        jButton1.setText("Encrypt File");
        jButton1.setName(""); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setBackground(java.awt.Color.white);
        jButton2.setForeground(java.awt.Color.blue);
        jButton2.setText("Decrypt File");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setBackground(java.awt.Color.white);
        jButton3.setForeground(java.awt.Color.blue);
        jButton3.setText("Test Encryption with Hex Data");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setBackground(java.awt.Color.white);
        jButton4.setForeground(java.awt.Color.blue);
        jButton4.setText("Test Decryption with Hex Data");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setBackground(java.awt.Color.white);
        jButton5.setForeground(java.awt.Color.blue);
        jButton5.setText("Exit");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jLabel1.setBackground(java.awt.Color.black);
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("BLOWFISH");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(162, 162, 162))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4)
                            .addComponent(jButton3))
                        .addGap(86, 86, 86))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(177, 177, 177))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Object[] s = { "Hexadecimal String", "Password" };
        int choice = JOptionPane.showOptionDialog(null,
                    "How would you like to proceed with Key?", "Select your option",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,
                    null, s, s[1]);
        if(choice==1)
        {
            String pass = JOptionPane.showInputDialog("Enter Password: ");
            int counter=0;
            while(counter<pass.length())
            {
		char c= pass.charAt(counter);
		key+=Integer.valueOf(String.valueOf((int)c), 16);
		counter++;
            }
        }
        else
        {
            String hexa = JOptionPane.showInputDialog("Enter Hexadecimal String: ");
            key = hexa;
        }
        
        int returnVal = jFileChooser1.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            file = jFileChooser1.getSelectedFile();
            try {
                BlowFish bfobj = new BlowFish();
                try {
                    bfobj.Calculation(key, file, 1);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "\nFile is Encrypted Successfully!\n\nTotal Elapsed Time: "+bfobj.tt+"s");
                }
            } catch (Exception ex) {
                System.out.println("problem accessing file"+file.getAbsolutePath());
            }
        } else {
        System.out.println("File access cancelled by user.");
        }  
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        Object[] s = { "Hexadecimal String", "Password" };
        int choice = JOptionPane.showOptionDialog(null,
                    "How would you like to proceed with Key?", "Select your option",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,
                    null, s, s[1]); 
        if(choice==1)
        {
            String pass = JOptionPane.showInputDialog("Enter Password: ");
            int counter=0;
            while(counter<pass.length())
            {
		char c= pass.charAt(counter);
		key+=Integer.valueOf(String.valueOf((int)c), 16);
		counter++;
            }
        }
        else
        {
            String hexa = JOptionPane.showInputDialog("Enter Hexadecimal String: ");
            key = hexa;
        }
        
        int returnVal = jFileChooser1.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            file = jFileChooser1.getSelectedFile();
            try {
                BlowFish bfobj = new BlowFish();
                try {
                    bfobj.Calculation(key, file, 2);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "\nFile is Decrypted Successfully!\n\nTotal Elapsed Time: "+bfobj.tt+"s");
                }
            } catch (Exception ex) {
                System.out.println("problem accessing file"+file.getAbsolutePath());
            }
        } else {
        System.out.println("File access cancelled by user.");
        }
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        Object[] s = { "Hexadecimal String", "Password" };
        int choice = JOptionPane.showOptionDialog(null,
                    "How would you like to proceed with Key?", "Select your option",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,
                    null, s, s[1]); 
        if(choice==1)
        {
            String pass = JOptionPane.showInputDialog("Enter Password: ");
            int counter=0;
            while(counter<pass.length())
            {
		char c= pass.charAt(counter);
		key+=Integer.valueOf(String.valueOf((int)c), 16);
		counter++;
            }
        }
        else
        {
            String hexa = JOptionPane.showInputDialog("Enter Hexadecimal String: ");
            key = hexa;
        }
        
        try {
                BlowFish bfobj = new BlowFish();
                try {
                    bfobj.Calculation(key, file, 3);
                } catch (Exception ex) {
                    Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (Exception ex) {
                System.out.println("problem accessing file"+file.getAbsolutePath());
            }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        Object[] s = { "Hexadecimal String", "Password" };
        int choice = JOptionPane.showOptionDialog(null,
                    "How would you like to proceed with Key?", "Select your option",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,
                    null, s, s[1]); 
        if(choice==1)
        {
            String pass = JOptionPane.showInputDialog("Enter Password: ");
            int counter=0;
            while(counter<pass.length())
            {
		char c= pass.charAt(counter);
		key+=Integer.valueOf(String.valueOf((int)c), 16);
		counter++;
            }
        }
        else
        {
            String hexa = JOptionPane.showInputDialog("Enter Hexadecimal String: ");
            key = hexa;
        }
        try {
                BlowFish bfobj = new BlowFish();
                try {
                    bfobj.Calculation(key, file, 4);
                } catch (Exception ex) {
                    Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (Exception ex) {
                System.out.println("problem accessing file"+file.getAbsolutePath());
            }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5MouseClicked

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
